version: '3.8'
services:
  signalforge:
    build: .
    ports:
      - "8080:80"
    environment:
      - TELEGRAM_BOT_TOKEN=8771510966:AAGsaZJhzefxDFmK5CHBLsIFnKt9nT4itgQ
      - TELEGRAM_CHAT_ID=6964954278
    volumes:
      - ./logs:/var/www/html/logs
